version: '3'

services:
  backend:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/eh-backend-api
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/sql:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:3306
  redis:
      image: "redis:latest"
      ports:
        - "${REDIS_PORT}:6379"
      volumes:
        - "./docker/redis:/data"
