// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package drivers

import (
	"adapter/controllers"
	"adapter/gateways/mysql"
	"app/usecases/interactors"
	"context"
	"github.com/labstack/echo"
)

// Injectors from wire.go:

func InitializeUserDriver(ctx context.Context) (User, error) {
	echoEcho := echo.New()
	inputFactory := NewInputFactory()
	repositoryFactory := NewRepositoryFactory()
	userApi := controllers.NewUserController(inputFactory, repositoryFactory)
	user := NewUserDriver(echoEcho, userApi)
	return user, nil
}

// wire.go:

func NewInputFactory() controllers.InputFactory {
	return interactors.NewUserInputPort
}

func NewRepositoryFactory() controllers.RepositoryFactory {
	return mysql.NewUserRepository
}
