// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package drivers

import (
	"context"
	"eh-backend-api/adapter/controllers"
	"eh-backend-api/adapter/controllers/auth"
	"eh-backend-api/adapter/controllers/schedule"
	"eh-backend-api/adapter/controllers/user"
	"eh-backend-api/adapter/gateways/mysql"
	"eh-backend-api/adapter/gateways/redis"
	"eh-backend-api/app/usecases/interactors"
	"github.com/labstack/echo"
)

// Injectors from wire.go:

func InitializeDriver(ctx context.Context) (Server, error) {
	echoEcho := echo.New()
	requestMapper := controllers.NewRequestMapper()
	authRepository := mysql.NewAnthRepository()
	userRepository := mysql.NewUserRepository()
	tokenRepository := redis.NewTokenRepository()
	authInputPort := interactors.NewAuthIputPort(authRepository, userRepository, tokenRepository)
	userInputPort := interactors.NewUserInputPort(userRepository)
	userApi := user.NewUserController(requestMapper, authInputPort, userInputPort)
	authApi := auth.NewAuthController(requestMapper, authInputPort)
	scheduleRepository := mysql.NewScheduleRepository()
	scheduleInputPort := interactors.NewScheduleInputPort(scheduleRepository)
	scheduleApi := schedule.NewScheduleController(requestMapper, authInputPort, scheduleInputPort)
	server := NewDriver(echoEcho, userApi, authApi, scheduleApi)
	return server, nil
}
