// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package drivers

import (
	"context"
	"eh-backend-api/adapter/controllers/user"
	"eh-backend-api/adapter/gateways/mysql"
	"eh-backend-api/app/usecases/interactors"
	"github.com/labstack/echo"
)

// Injectors from wire.go:

func InitializeUserDriver(ctx context.Context) (Server, error) {
	echoEcho := echo.New()
	inputFactory := NewInputFactory()
	repositoryFactory := NewRepositoryFactory()
	userApi := user.NewUserController(inputFactory, repositoryFactory)
	server := NewUserDriver(echoEcho, userApi)
	return server, nil
}

// wire.go:

func NewInputFactory() user.InputFactory {
	return interactors.NewUserInputPort
}

func NewRepositoryFactory() user.RepositoryFactory {
	return mysql.NewUserRepository
}
